# Common Parameters
Common_Param:
  SigType: ART # Types of signals to train on: ART, PLETH, II.
  CompSize: 500 # Signal compression length (unit 0.01 second) "Valid values: 100, 200, 300, 400, 500, 600, 700, 800"
  MaskingRate: 0.00 # The sequence masking ratio during training.
  NoiseStd: 0.00 # Gaussian noise standard deviation across entire signal.
  MaskStd: 0.00 # Gaussian noise standard deviation applied to masked signal.
  ReparaStd: 0.1 # Gaussian noise standard deviation for reparameterization trick.
  Capacity_Z: 0.05 # KLD control capacity for Z.
  Capacity_Fc: 0.005 # KLD control capacity for Fc.
  FcLimit: 1.0 # Upper threshold for frequency.
  DecayH: 0.00 # High-pass filter decay.
  DecayL: 0.00 # Low-pass filter decay.
  
  BatSize: 3000 # Batch size for training.
  NEpochs: 5000 # Number of epochs.
  LossType: 'Default' # Loss type (Default or FACLosses).

  # The parameters below are related to dynamic loss control; refer to the RelLossWeight class in utility.py.
  # Loss Weights
  WRec: 1 # Reconstruction loss weight.
  WFeat: 1 # Feature loss weight.
  WZ: 1 # Z loss weight.
  WFC: 1 # FC loss weight.

  # If MnW* and MxW* are the same, loss scaling remains constant without dynamic adjustments ; refer to the RelLossWeight class in utility.py.
  # Minimum Weights
  MnWRec: 1 # Min reconstruction loss weight.
  MnWFeat: 2 # Min feature loss weight.
  MnWZ: 0.00001 # Min Z loss weight.
  MnWFC: 1.0 # Min FC loss weight.

  # Maximum Weights
  MxWRec: 1 # Min reconstruction loss weight.
  MxWFeat: 2 # Min feature loss weight.
  MxWZ: 0.00001 # Min Z loss weight.
  MxWFC: 1.0 # Min FC loss weight.

# Model-Specific Parameters
Models:
  SKZFC_ART_1_30_500_Mimic:
    DataSource: Mimic3 # The data source.
    LatDim: 30 # Dimensionality of the latent variable Z.
    Depth: 1 # Depth of cascading filters.
    SpecLosses: ['SKZ','FC'] # Specific loss nicknames.

  SKZFC_ART_1_50_500_Mimic:
    DataSource: Mimic3 
    LatDim: 50
    Depth: 1
    SpecLosses: ['SKZ','FC'] # Specific loss nicknames.

  SKZFC_ART_2_30_500_Mimic:
    DataSource: Mimic3 
    LatDim: 30
    Depth: 2
    SpecLosses: ['SKZ','FC'] # Specific loss nicknames.

  SKZFC_ART_2_50_500_Mimic:
    DataSource: Mimic3 
    LatDim: 50
    Depth: 2
    SpecLosses: ['SKZ','FC'] # Specific loss nicknames.
    
  SKZFC_ART_1_30_500_VitalDB:
    DataSource: VitalDB
    LatDim: 30 
    Depth: 1 
    SpecLosses: ['SKZ','FC'] # Specific loss nicknames.
    
  SKZFC_ART_1_50_500_VitalDB:
    DataSource: VitalDB
    LatDim: 50
    Depth: 1
    SpecLosses: ['SKZ','FC'] # Specific loss nicknames.
    
  SKZFC_ART_2_30_500_VitalDB:
    DataSource: VitalDB 
    LatDim: 30
    Depth: 2
    SpecLosses: ['SKZ','FC'] # Specific loss nicknames.
        
  SKZFC_ART_2_50_500_VitalDB:
    DataSource: VitalDB 
    LatDim: 50
    Depth: 2
    SpecLosses: ['SKZ','FC'] # Specific loss nicknames.



  # Ablation models
  SKZ_ART_2_50_500_Mimic:
    DataSource: VitalDB 
    LatDim: 50
    Depth: 2
    SpecLosses: ['SKZ'] # Specific loss nicknames.

  FC_ART_2_50_500_Mimic:
    DataSource: VitalDB 
    LatDim: 50
    Depth: 2
    SpecLosses: ['FC'] # Specific loss nicknames.
