# The list of common objects subject to class serialization.
Common_Info: ['SubResDic', 'AggResDic', 'BestZsMetrics', 'TrackerCand', 'CandFreqIDs', 
              'PostSamp', 'GenBatchSize', 'GPU'] 

# Common Parameters
Common_Param:
  NSelZ: [1]    # The size of js to be selected at the same time (default: 1).
  ReparaStd: 1           # The standard deviation value for Gaussian noise generation used in the reparametrization trick.
  ReparaStdZj: 1         # The size of the standard deviation when sampling Zj (Samp_ZjRPT ~ N(0, ReparaStdZj)).
  MaxFreq: 100           # The maximum frequency value within the analysis range (default = 51).
  MinFreq: 1             # The minimum frequency value within the analysis range (default = 1).
  NMiniBat: 50           # The size of the mini-batch, splitting the task into N pieces of size NMiniBat.
  SimSize: 1             # The number of generations (i.e., samplings) within the mini-batch.
  EvalDataSize: 10000    # The number of observations in the evaluation data
  SampBatchSize: 10000   # The batch size during prediction of the sampling model.
  SigDim: 1000           # The dimensionality of the signal.
  WindowSize: 3          # The window size when calculating permutation entropy (default: 3)
  GPU: True              # GPU vs CPU during model predictions (i.e., for SampModel and GenModel). "The CPU is strongly recommended for optimal precision."
  SelMetricType: 'KLD'   # The type of metric used for selecting Zs and ancillary data. 
  SelMetricCut: 1.       # MetricCut: The threshold value for selecting Zs whose Entropy or KLD of PSD is less than the MetricCut.

# Model-Specific Parameters
Models:
  ConVAE_II_30_Mimic:
    TestDataSource: VitalDB  # The data source for testing and visualization.
    GenBatchSize: 10000      # The batch size during prediction of the generation model.
    NSubGen: 50              # The number of generations (i.e., samplings) within a sample.
    NParts: 10               # The number of partitions (i.e., samplings) in generations within a sample.
    SecDataType: 'CONDIN'    # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: ['I_V_CONsZj', 'I_S_CONsZj', 'LatDim', 'NSelZ'] # The list of specific objects subject to class serialization.

  TCVAE_II_30_Mimic:
    TestDataSource: VitalDB # The data source for testing and visualization.
    GenBatchSize: 10000     # The batch size during prediction of the generation model.
    NSubGen: 1              # The number of generations (i.e., samplings) within a sample.
    NParts: 1               # The number of partitions (i.e., samplings) in generations within a sample.
    SecDataType: null       # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: ['LatDim', 'NSelZ']   # The list of specific objects subject to class serialization.

  FACVAE_II_30_Mimic:
    TestDataSource: VitalDB # The data source for testing and visualization.
    GenBatchSize: 10000     # The batch size during prediction of the generation model.
    NSubGen: 1              # The number of generations (i.e., samplings) within a sample.
    NParts: 1               # The number of partitions (i.e., samplings) in generations within a sample.
    SecDataType: null       # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: []           # The list of specific objects subject to class serialization.
    
  VDVAE_II_30_Mimic:
    TestDataSource: VitalDB # The data source for testing and visualization.
    GenBatchSize: 10000     # The batch size during prediction of the generation model.
    NSubGen: 1              # The number of generations (i.e., samplings) within a sample.
    NParts: 1               # The number of partitions (i.e., samplings) in generations within a sample.
    SecDataType: null       # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: ['LatDim', 'NSelZ'] # The list of specific objects subject to class serialization.
    
  ConVAE_II_30_VitalDB:
    TestDataSource: Mimic3  # The data source for testing and visualization.
    GenBatchSize: 10000      # The batch size during prediction of the generation model.
    NSubGen: 50              # The number of generations (i.e., samplings) within a sample.
    NParts: 10               # The number of partitions (i.e., samplings) in generations within a sample.
    SecDataType: 'CONDIN'    # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: ['I_V_CONsZj', 'I_S_CONsZj', 'LatDim', 'NSelZ'] # The list of specific objects subject to class serialization.

  TCVAE_II_30_VitalDB:
    TestDataSource: Mimic3 # The data source for testing and visualization.
    GenBatchSize: 10000     # The batch size during prediction of the generation model.
    NSubGen: 1              # The number of generations (i.e., samplings) within a sample.
    NParts: 1               # The number of partitions (i.e., samplings) in generations within a sample.
    SecDataType: null       # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: ['LatDim', 'NSelZ']  # The list of specific objects subject to class serialization.

  FACVAE_II_30_VitalDB:
    TestDataSource: Mimic3 # The data source for testing and visualization.
    GenBatchSize: 10000     # The batch size during prediction of the generation model.
    NSubGen: 1              # The number of generations (i.e., samplings) within a sample.
    NParts: 1               # The number of partitions (i.e., samplings) in generations within a sample.
    SecDataType: null       # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: ['LatDim', 'NSelZ']  # The list of specific objects subject to class serialization.
    
  VDVAE_II_30_VitalDB:
    TestDataSource: Mimic3 # The data source for testing and visualization.
    GenBatchSize: 10000     # The batch size during prediction of the generation model.
    NSubGen: 1              # The number of generations (i.e., samplings) within a sample.
    NParts: 1               # The number of partitions (i.e., samplings) in generations within a sample.
    SecDataType: null       # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: ['LatDim', 'NSelZ']  # The list of specific objects subject to class serialization.
