# The list of common objects subject to class serialization.
Common_Info: ['SubResDic', 'AggResDic', 'BestZsMetrics', 'TrackerCand', 'CandFreqIDs', 
              'PostSamp', 'GenBatchSize', 'GPU'] 

# Common Parameters
Common_Param:
  MaxFreq: 100           # The maximum frequency value within the analysis range (default = 51).
  MinFreq: 1             # The minimum frequency value within the analysis range (default = 1).
  NMiniBat: 50           # The size of the mini-batch, splitting the task into N pieces of size NMiniBat.
  SimSize: 1             # The number of generations (i.e., samplings) within the mini-batch.
  EvalDataSize: 10000    # The number of observations in the evaluation data
  SampBatchSize: 10000   # The batch size during prediction of the sampling model.
  SigDim: 1000           # The dimensionality of the signal.
  WindowSize: 3          # The window size when calculating permutation entropy (default: 3)
  GPU: True              # GPU vs CPU during model predictions (i.e., for SampModel and GenModel). "The CPU is strongly recommended for optimal precision."
  SelMetricType: 'KLD'   # The type of metric used for selecting Zs and ancillary data. 
  SelMetricCut: 1.       # MetricCut: The threshold value for selecting Zs whose Entropy or KLD of PSD is less than the MetricCut.

# Model-Specific Parameters
Models:
  Wavenet_ART_Mimic:
    TestDataSource: VitalDB  # The data source for testing and visualization.
    GenBatchSize: 500       # The batch size during prediction of the generation model.
    NSubGen: 50              # The number of generations (i.e., samplings) within a sample.
    NParts: 10               # The number of partitions (i.e., samplings) in generations within a sample.
    NSplitBatch: 50          # The number of batch splits.
    SecDataType: 'CONDIN'    # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: []            # The list of specific objects subject to class serialization.  

  Wavenet_ART_VitalDB:
    TestDataSource: Mimic3  # The data source for testing and visualization.
    GenBatchSize: 500       # The batch size during prediction of the generation model.
    NSubGen: 50              # The number of generations (i.e., samplings) within a sample.
    NParts: 10               # The number of partitions (i.e., samplings) in generations within a sample.
    NSplitBatch: 50          # The number of batch splits.
    SecDataType: 'CONDIN'    # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: []            # The list of specific objects subject to class serialization.  

  DiffWave_ART_Mimic:
    TestDataSource: VitalDB  # The data source for testing and visualization.
    GenBatchSize: 2500       # The batch size during prediction of the generation model.
    NSubGen: 50              # The number of generations (i.e., samplings) within a sample.
    NParts: 10               # The number of partitions (i.e., samplings) in generations within a sample.
    GenSteps: 100            # The number of Restoration steps. 
    SNR_cutoff: 10           # SNR cutoff for determining the start T point of reverse diffusion. 
    StepInterval: 2          # The interval for skipping steps in the reverse process (to be specified).
    SecDataType: 'CONDIN'    # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: []            # The list of specific objects subject to class serialization.  
    
  DiffWave_ART_VitalDB:
    TestDataSource: Mimic3  # The data source for testing and visualization.
    GenBatchSize: 2500       # The batch size during prediction of the generation model.
    NSubGen: 50              # The number of generations (i.e., samplings) within a sample.
    NParts: 10               # The number of partitions (i.e., samplings) in generations within a sample.
    GenSteps: 100             # The number of Restoration steps. 
    SNR_cutoff: 10           # SNR cutoff for determining the start T point of reverse diffusion.
    StepInterval: 2          # The interval for skipping steps in the reverse process (to be specified).
    SecDataType: 'CONDIN'    # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: []            # The list of specific objects subject to class serialization.  

  VDWave_ART_Mimic:
    TestDataSource: VitalDB  # The data source for testing and visualization.
    GenBatchSize: 2500       # The batch size during prediction of the generation model.
    NSubGen: 50              # The number of generations (i.e., samplings) within a sample.
    NParts: 10               # The number of partitions (i.e., samplings) in generations within a sample.
    GenSteps: 100             # The number of Restoration steps. 
    SNR_cutoff: 10           # SNR cutoff for determining the start T point of reverse diffusion.
    StepInterval: 2          # The interval for skipping steps in the reverse process (to be specified).
    SecDataType: 'CONDIN'    # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: []            # The list of specific objects subject to class serialization.  

  VDWave_ART_VitalDB:
    TestDataSource: Mimic3  # The data source for testing and visualization.
    GenBatchSize: 2500       # The batch size during prediction of the generation model.
    NSubGen: 50              # The number of generations (i.e., samplings) within a sample.
    NParts: 10               # The number of partitions (i.e., samplings) in generations within a sample.
    GenSteps: 100             # The number of Restoration steps. 
    SNR_cutoff: 10           # SNR cutoff for determining the start T point of reverse diffusion.
    StepInterval: 2          # The interval for skipping steps in the reverse process (to be specified).
    SecDataType: 'CONDIN'    # The ancillary data-type: Use 'FCIN' for FC values or 'CONDIN' for conditional inputs such as power spectral density.
    Spec_Info: []            # The list of specific objects subject to class serialization.   